name: Update Spring Boot Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  update:
    name: Update Spring Boot Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Install NPM deps.
        run: npm install axios xml2js octokit yaml semver
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node ./hack/update-springboot-platform.js

